- name: Installing Docker and Docker Compose
  hosts: workers
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes
        shell: usermod -aG docker $USER
      notify: Docker installed  

  handlers:
    - name: Docker installed
      apt:
        name: docker-compose
        state: present  
